[packages]
appimage = [
		"https://github.com/ppy/osu/releases/latest/download/osu.appimage"
]
brew = [
		"rancher",
		"constitution",
		"soft-serve",
		"gum",
		"hocusfocus",
		"evoke",
		"zoxide",
		"viu",
		"feh",
		"yt-dlp",
		"vhs",
		"glow",
		"charmbracelet/tap/freeze",
		"aerc",
		"yazi",
		"grex",
		"jrnl",
		"croc"
]
flatpak = [
		"org.prismlauncher.PrismLauncher", 
		"one.ablaze.floorp", 
		"md.obsidian.Obsidian", 
		"org.kde.audiotube", 
		"org.gnome.World.Secrets", 
		"app.zen_browser.zen",
		"org.kde.kdenlive",
		"io.missioncenter.MissionCenter",
		"cc.arduino.IDE2",
		"it.mijorus.gearlever",
		"org.libreoffice.LibreOffice",
		"org.nickvision.tubeconverter",
		"de.schmidhuberj.tubefeeder",
		"de.haeckerfelix.Fragments",
		"org.cockpit_project.CockpitClient",
		"org.gnome.World.PikaBackup",
		"com.github.iwalton3.jellyfin-media-player",
		"org.videolan.VLC",
		"com.unicornsonlsd.finamp",
		"org.freedesktop.Platform.ffmpeg-full",
		"org.freedesktop.Platform.VulkanLayer.MangoHud",
		"com.github.tchx84.Flatseal",
		"com.belmoussaoui.Authenticator",
		"com.mardojai.ForgeSparks",
		"com.modrinth.ModrinthApp",
		"net.ankiweb.Anki",
		"menu.kando.Kando"
]
pacman = [
		"obs-studio", 
		"xdg-desktop-portal-hyprland", 
		"hyprpolkitagent", 
		"niri", 
		"waybar", 
		"wofi", 
		"swww", 
		"nemo", 
		"steam", 
		"ghostty", 
		"qt5ct", 
		"nwg-look", 
		"sassc",  
		"protobuf", 
		"cmark-gfm", 
		"bat", 
		"network-manager-applet", 
		"fastfetch", 
		"openh264",
		"papirus-icon-theme",
		"fuse2",
		"tmux",
		"cava",
		"cmatrix",
		"nwg-displays",
		"cups",
		"cups-filters",
		"cups-browsed",
		"cups-pdf",
		"gutenprint",
		"system-config-printer",
		"foomatic-db-engine",
		"foomatic-db-ppds",
		"dunst",
		"rhythmbox",
		"eza",
		"plymouth",
		"handbrake",
		"handbrake-cli",
		"libdvdcss",
		"rclone",
		"swaync",
		"supertuxkart",
		"bluez",
		"blueman",
		"libvirt",
		"qemu",
		"virt-manager",
		"go",
		"fuzzel",
		"nemo-share",
		"nemo-preview",
		"nemo-emblems",
		"nemo-audio-tab",
		"nemo-fileroller",
		"python3",
		"uv",
		"espeak-ng",
		"speech-dispatcher",
		"audacity",
		"pavucontrol",
		"teeworlds",
		"grim",
		"slurp",
		"less",
		"man",
		"vlc",
		"figlet",
		"hyprland",
		"hyprlock",
		"hyprpaper",
		"hyprcursor",
		"loupe",
		"ncdu",
		"kdeconnect",
		"ladybird-git",
		"7zip",
		"wine",
		"winetricks",
		"gdisk",
		"gparted",
		"partitionmanager",
		"dosfstools",
		"nushell",
		"blesh",
		"gnome-disk-utility",
		"quickshell"
]
aur = [
		"vicinae-bin",
		"neovim-nightly-bin",
		"blockbench-bin",
		"waydroid",
		"lf-git",
		"pipes.sh",
		"wlogout",
		"makemkv",
		"waybar-updates",
		"downgrade",
		"pix",
		"mangohud",
		"nintendo-udev",
		"hid-nintendo-nso-dkms",
		"joycond-git",
		"cbonsai",
		"tofi",
		"vscodium-bin",
		"squeezelite",
		"highscore-git",
		"gnome-games-meta",
		"lutgen-bin",
		"communique",
		"craftos-pc",
		"dms-shell-bin"
]
