[packages]
appimage = [
		"https://github.com/ppy/osu/releases/latest/download/osu.appimage"
]
flatpak = [
		"org.prismlauncher.PrismLauncher", 
		"one.ablaze.floorp", 
		"md.obsidian.Obsidian", 
		"org.kde.audiotube", 
		"org.gnome.World.Secrets", 
		"app.zen_browser.zen",
		"org.kde.kdenlive",
		"io.missioncenter.MissionCenter",
		"cc.arduino.IDE2",
		"it.mijorus.gearlever",
		"org.libreoffice.LibreOffice",
		"org.gnome.Rhythmbox3",
		"org.nickvision.tubeconverter",
		"de.schmidhuberj.tubefeeder",
		"de.haeckerfelix.Fragments"
]
pacman = [
		"hyprland", 
		"hyprpaper", 
		"hyprlock", 
		"obs-studio", 
		"hyprcursor", 
		"xdg-desktop-portal-hyprland", 
		"hyprpolkitagent", 
		"niri", 
		"waybar", 
		"wofi", 
		"swww", 
		"nemo", 
		"steam", 
		"ghostty", 
		"gnome-tweaks", 
		"qt5ct", 
		"nwg-look", 
		"sassc",  
		"protobuf", 
		"cmark-gfm", 
		"bat", 
		"wlogout", 
		"kde-connect", 
		"network-manager-applet", 
		"fastfetch", 
		"openh264",
		"papirus-icon-theme",
		"fuse2",
		"tmux",
		"cava",
		"cmatrix",
		"nwg-displays",
		"cups",
		"cups-filters",
		"cups-browsed",
		"cups-pdf",
		"gutenprint",
		"system-config-printer",
		"foomatic-db-engine",
		"foomatic-db-ppds"
]
aur = [
		"vicinae",
		"neovim-nightly-bin",
		"blockbench-bin",
		"waydroid"
]
