[packages]
appimage = [
	"https://github.com/ppy/osu/releases/latest/download/osu.appimage"
]
brew = [
	"stikypiston/formulae/rancher",
	"stikypiston/formulae/constitution",
	"soft-serve",
	"gum",
	"stikypiston/formulae/hocusfocus",
	"stikypiston/formulae/evoke",
	"zoxide",
	"viu",
	"feh",
	"yt-dlp",
	"vhs",
	"glow",
	"charmbracelet/tap/freeze",
	"aerc",
	"yazi",
	"grex",
	"jrnl",
	"croc",
	"stikypiston/formulae/redcards",
	"sysbench",
	"pkl",
	"swift",
	"pkl-lsp",
	"gh",
	"stikypiston/formulae/dotkeeper",
	"tlrc",
	"delta",
	"lazygit",
	"stan-breaks/ytsurf/ytsurf",
	"stikypiston/formulae/dotkeeper-tui",
	"luarocks",
	"npm",
	"ripgrep",
	"timewarrior",
	"helix",
	"git-lfs",
	"utftex",
	"ncdu",
	"stikypiston/formulae/chess-tui",
	"stockfish",
	"yarn",
	"w3m",
	"amfora",
	"gleam",
	"erlang",
	"stikypiston/formulae/recall",
	"zinit",
	"bob",
	"stikypiston/formulae/fastcards",
	"asciinema",
	"stikypiston/formulae/pricetag",
	"fd",
	"stikypiston/formulae/bobafm",
	"dart-sdk"
]
flatpak = [
	"org.prismlauncher.PrismLauncher", 
	"md.obsidian.Obsidian", 
	"org.gnome.World.Secrets", 
	"app.zen_browser.zen",
	"org.kde.kdenlive",
	"io.missioncenter.MissionCenter",
	"cc.arduino.IDE2",
	"it.mijorus.gearlever",
	"org.libreoffice.LibreOffice",
	"org.nickvision.tubeconverter",
	"de.schmidhuberj.tubefeeder",
	"de.haeckerfelix.Fragments",
	"org.cockpit_project.CockpitClient",
	"org.gnome.World.PikaBackup",
	"com.github.iwalton3.jellyfin-media-player",
	"org.videolan.VLC",
	"com.unicornsonlsd.finamp",
	"org.freedesktop.Platform.ffmpeg-full",
	"org.freedesktop.Platform.VulkanLayer.MangoHud",
	"com.github.tchx84.Flatseal",
	"com.belmoussaoui.Authenticator",
	"com.mardojai.ForgeSparks",
	"com.modrinth.ModrinthApp",
	"net.ankiweb.Anki",
	"menu.kando.Kando",
	"org.fedoraproject.MediaWriter",
	"org.localsend.localsend_app",
	"io.github.giantpinkrobots.varia",
	"org.freedesktop.Platform.VulkanLayer.MangoHud//24.08",
	"org.vinegarhq.Vinegar",
	"org.vinegarhq.Sober",
	"org.winehq.Wine"
]
pacman = [
	"obs-studio", 
	"xdg-desktop-portal-hyprland", 
	"hyprpolkitagent", 
	"niri", 
	"waybar", 
	"wofi", 
	"swww", 
	"nemo", 
	"steam", 
	"ghostty", 
	"qt5ct", 
	"nwg-look", 
	"sassc",  
	"protobuf", 
	"cmark-gfm", 
	"bat", 
	"network-manager-applet", 
	"fastfetch", 
	"openh264",
	"papirus-icon-theme",
	"fuse2",
	"tmux",
	"cava",
	"cmatrix",
	"nwg-displays",
	"cups",
	"cups-filters",
	"cups-browsed",
	"cups-pdf",
	"gutenprint",
	"system-config-printer",
	"foomatic-db-engine",
	"foomatic-db-ppds",
	"dunst",
	"rhythmbox",
	"eza",
	"plymouth",
	"handbrake",
	"handbrake-cli",
	"libdvdcss",
	"rclone",
	"swaync",
	"supertuxkart",
	"bluez",
	"blueman",
	"libvirt",
	"qemu",
	"virt-manager",
	"go",
	"fuzzel",
	"nemo-share",
	"nemo-emblems",
	"nemo-audio-tab",
	"nemo-fileroller",
	"python3",
	"uv",
	"espeak-ng",
	"speech-dispatcher",
	"pavucontrol",
	"teeworlds",
	"grim",
	"slurp",
	"less",
	"man",
	"vlc",
	"figlet",
	"hyprland",
	"hyprlock",
	"hyprpaper",
	"hyprcursor",
	"loupe",
	"kdeconnect",
	"ladybird-git",
	"7zip",
	"wine",
	"winetricks",
	"gdisk",
	"gparted",
	"partitionmanager",
	"dosfstools",
	"nushell",
	"gnome-disk-utility",
	"quickshell",
	"ttf-jetbrains-mono-nerd",
	"starship",
	"ly",
	"lxappearance",
	"rmpc",
	"mpd",
	"ncmpcpp",
	"mpd-mpris",
	"dracut",
	"btop",
	"tree",
	"vlc-plugin-ffmpeg",
	"hyprpicker",
	"gnome-boxes",
	"edk2-ovmf",
	"tree-sitter",
	"tree-sitter-cli",
	"ruby-lsp",
	"lua-language-server",
	"fish",
	"ueberzugpp",
	"blender",
	"uxplay",
	"zsh",
	"imagemagick",
	"solvespace",
	"zathura",
	"zathura-cb",
	"zathura-djvu",
	"zathura-pdf-mupdf",
	"zathura-ps",
	"xdg-desktop-portal-gnome",
	"xwayland-satellite",
	"vulkan-intel",
	"lib32-vulkan-intel",
	"vulkan-icd-loader",
	"vulkan-tools",
	"lib32-mesa",
	"lib32-vulkan-icd-loader"
]
aur = [
	"vicinae-bin",
	"blockbench-bin",
	"waydroid",
	"lf-git",
	"pipes.sh",
	"wlogout",
	"waybar-updates",
	"downgrade",
	"pix",
	"mangohud",
	"nintendo-udev",
	"hid-nintendo-nso-dkms",
	"joycond-git",
	"cbonsai",
	"vscodium-bin",
	"squeezelite",
	"highscore-git",
	"gnome-games-meta",
	"lutgen-bin",
	"communique",
	"craftos-pc",
	"dms-shell-bin",
	"plymouth-theme-hud-3-git",
	"plymouth-theme-spinner-alt-git",
	"songfetch",
	"alertify",
	"blesh",
	"quickemu",
	"folder-color-nemo",
	"dmg2img",
	"indicator-stickynotes",
	"catppuccin-cursors-mocha",
]
